server:
  port: 9000


spring:
  application:
    name: books
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: 220702
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update

debug: true
