server:
  port: 9000

spring:
  application:
    name: books
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: create-drop

debug: true
